version: "3"

services:
  app:
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`devminer.xyz`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.services.homepage-service.loadbalancer.server.port=3000
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: web_default
    external: true
